### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by Muschasgrazias** [FlyingCampDesign/aardvark_py#1]
Hey,

Are you still working on this repository?

Because https://www.totalphase.com/products/aardvark-software-api/ supports now Python 3.

Is it possible to add this feature? (I can help if you need some)

Best regards

**Comment by cdwilson** [comment]
@Muschasgrazias thanks for the heads up.  Yes, I'd like to keep this project up to date with the latest API.  I'll try to take a look at updating it this weekend.  If you're eager, feel free to send me a pull request.

Also, I've been meaning to see if there is a more 'pythonic' way to bundle the shared libraries in the python package (i.e. via setuptools or some other mechanism)--this may be a good opportunity to make that change as well.

TBH, I really wish Total Phase themselves would simply provide an official PyPI project that THEY supported...

**Comment by cdwilson** [comment]
I just took a quick look at the files, and I don't think the TotalPhase API versions are correct.  For example, the Python bindings show

```
#==========================================================================
# VERSION
#==========================================================================
AA_API_VERSION    = 0x050a   # v5.10
AA_REQ_SW_VERSION = 0x050a   # v5.10
```

and the `CHANGES.txt` file doesn't even mention the v5.30 release at all...

I sent a support request to TotalPhase to get some clarification.

**Comment by Muschasgrazias** [comment]
Hey,

Sorry I removed my comment again -_-

I think so as well, they should support a python API or at least make an repository like you did.

I need some time to read into your implementation, but I will update you if I get something to work!

Best regards

**Comment by cdwilson** [comment]
I got a response from Total Phase.  

> There are 3 different versions maintained for the API. These are:
> 
> * AA_API_VERSION
> * AA_REQ_SW_VERSION
> * AA_SW_VERSION
>
> Of these versions, the actual API version (in the shared library) is stored under AA_SW_VERSION and is not visible to the users. The AA_REQ_SW_VERSION is the minimum API version required by the current wrapper API and AA_API_VERSION is the version on the current API wrapper. So to summarize, the actual API version i.e. v5.30 is available under AA_SW_VERSION.

TBH, it's been a while since I've looked at this, and I forgot that these versions can be different...

```python
>>> print "%d.%d" % (((aardvark_py.AA_API_VERSION >> 8) & 0xFF), (aardvark_py.AA_API_VERSION & 0xFF))
5.10
>>> print "%d.%d" % (((aardvark_py.AA_REQ_SW_VERSION >> 8) & 0xFF), (aardvark_py.AA_REQ_SW_VERSION & 0xFF))
5.10
>>> print "%d.%d" % (((aardvark_py.AA_SW_VERSION >> 8) & 0xFF), (aardvark_py.AA_SW_VERSION & 0xFF))
5.30
```

**Comment by cdwilson** [comment]
@Muschasgrazias I updated the dev branch with the latest 5.30 API, but I haven't had a chance to test it yet.  Please test it out and let me know if it works for you.

FYI, I haven't used Python 3 until this point, and for some reason, `python setup.py test` fails in Python 3, but not in Python 2.  If you have any idea why it's failing in Python 3, let me know.

**Comment by Muschasgrazias** [comment]
I will try it on monday I'm on holidays over the weekend.

Thanks for updating!

Best regards

**Comment by Muschasgrazias** [comment]
Hi,

It is working for me on my side, I am not sure if I covered all functions though (tested by my program):

array
aa_open
aa_configure
aa_i2c_bitrate
aa_i2cpullup
aa_find_devices
aa_i2c_bus_timeout
aa_i2c_write
aa_i2c_read
aa_close

I don't know why, but it feels faster/better than the old version.

You said something about reworking your code, could you elaborate so I can contribute if necessary.

Best regards

**Comment by cdwilson** [comment]
Uploaded 5.30.0 to PyPI

https://pypi.python.org/pypi/aardvark-py/5.30.0
