### ISSUE TITLE
New pip release

### ISSUE THREAD

**Issue by Muschasgrazias** [FlyingCampDesign/aardvark_py#2]
Hey,

Could you please release the new version where python 3 is possible?

Thanks,
BR

**Comment by cdwilson** [comment]
@Muschasgrazias sorry, I was on vacation for the last two weeks and just got back.  I'll try to get this released in the next day or two.

**Comment by cdwilson** [comment]
I uploaded a development release to https://test.pypi.org/project/aardvark-py/  Can you do me a favor and test this out?

`pip install --index-url https://test.pypi.org/simple/ aardvark_py`

If everything works for you, I'll release it on the real PyPI site.

**Comment by Muschasgrazias** [comment]
I used pip3 install https://github.com/FlyingCampDesign/aardvark_py/archive/dev.zip

Version aardvark-py==5.30.0.dev0, should be essentially the same.

It worked for me best regards

**Comment by cdwilson** [comment]
Uploaded 5.30.0 to PyPI

https://pypi.python.org/pypi/aardvark-py/5.30.0
